version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'codeboards'
      POSTGRES_PASSWORD: '123456'
volumes:
  db_data:
